{
  "status" : "fail",
  "tests" : [
    {
      "name" : "testAdd",
      "status" : "pass",
      "test_code" : "XCTAssertEqual(sum(2, 3), 5, \"2+3 should equal 5\")"
    },
    {
      "name" : "testSub",
      "status" : "pass",
      "test_code" : "XCTAssertEqual(sub(2, 3), -1)"
    },
    {
      "name" : "testMul",
      "status" : "pass",
      "test_code" : "XCTAssertEqual(mul(3, 2), 6)"
    },
    {
      "message" : "/solution/Tests/MultipleWithExceptionTests/MultipleWithExceptionTests.swift:19: error: MultipleWithExceptionTests.testThrow : XCTAssertEqual threw error \"testError(\"Oh noes! Div by zeroes!!!\")\" -",
      "name" : "testThrow",
      "status" : "fail",
      "test_code" : "XCTAssertEqual(try throwErr(2, 0), 6)"
    }
  ],
  "version" : 3
}